<?php
/**
 * GoMage LegalPerson Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2017 GoMage (https://www.gomage.com)
 * @author       GoMage
 * @license      https://www.gomage.com/license-agreement/  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use
 * @version      Release: 1.0.0
 * @since        Class available since Release 1.0.0
 */
?>
<script type="text/javascript">
    //<![CDATA[
    optionalZipCountries = <?php echo $this->helper('directory')->getCountriesWithOptionalZip(true) ?>;

    gmLegalPersonConfig = <?php echo $this->helper('gomage_legalperson')->getConfig(true) ?>;

    gmLegalPerson = new GoMage.LegalPerson(gmLegalPersonConfig, 'tr', 'country_id');

    function onAddressCountryChanged(countryElement) {
        var zipElementId = countryElement.id.replace(/country_id/, 'postcode');

        // Ajax-request and normal content load compatibility
        if ($(zipElementId) != undefined) {
            setPostcodeOptional($(zipElementId), countryElement.value);
            gmLegalPerson.onAddressCountryChanged(countryElement);
        } else {
            Event.observe(window, "load", function () {
                setPostcodeOptional($(zipElementId), countryElement.value);
                gmLegalPerson.onAddressCountryChanged(countryElement);
            });
        }
    }

    function setPostcodeOptional(zipElement, country) {
        if (optionalZipCountries.indexOf(country) != -1) {
            while (zipElement.hasClassName('required-entry')) {
                zipElement.removeClassName('required-entry');
            }
            zipElement.up(1).down('label > span.required').hide();
        } else {
            zipElement.addClassName('required-entry');
            zipElement.up(1).down('label > span.required').show();
        }
    }

    varienGlobalEvents.attachEventHandler("address_country_changed", onAddressCountryChanged);
    //]]>
</script>